version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: go_rate_limiter_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: